# Generated by Django 5.2.5 on 2025-08-23 21:23

import django_extensions.db.fields
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("slug", models.SlugField(blank=True, verbose_name="Tenant URL Name")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "name",
                    models.CharField(help_text="name of the client", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="organisation email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="organisation description", null=True
                    ),
                ),
                (
                    "organisation_code",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quater", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DISAPPROVED", "Disapproved"),
                            ("REMOVED", "Removed"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "ordering": ("created",),
                "abstract": False,
            },
        ),
    ]
